import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronRight, Mail, Plus, Search, X } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import PortalShell from "../components/PortalShell";
import { associateClientProject, ClientDetail, ClientListItem, getClient, getClients, getProjects, Project, removeClientProject, saveClientNotes } from "../api/projects";
import { phaseLabel } from "../projectPhases";

const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join("").toLocaleUpperCase();
export function ClientsPage() {
  const [clients, setClients] = useState<ClientListItem[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [invite, setInvite] = useState(false); const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const navigate = useNavigate();
  useEffect(() => { getClients().then(setClients).catch(e=>setError(e.message)); }, []);
  const filtered = useMemo(() => clients.filter(c => `${c.displayName} ${c.email}`.toLocaleLowerCase("pt-PT").includes(query.toLocaleLowerCase("pt-PT"))), [clients,query]);
  const submitInvite = (e: FormEvent) => { e.preventDefault(); if (!email) return; setSent(true); };
  return <PortalShell><header className="mock-page-header"><div><p className="mock-eyebrow">Relações</p><h1>Clientes</h1><p>Consulta os clientes do atelier e os projetos associados.</p></div><button className="primary-action" onClick={()=>{setInvite(true);setSent(false);setEmail("");}}><Plus size={18}/>Adicionar cliente</button></header><div className="mock-toolbar"><label className="mock-search"><Search size={19}/><span className="sr-only">Pesquisar clientes</span><input type="search" placeholder="Pesquisar por nome ou email" value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button type="button" aria-label="Limpar pesquisa" onClick={()=>setQuery("")}><X size={16}/></button>}</label><span className="mock-result-count">{filtered.length} clientes</span></div>{error && <p role="alert">{error}</p>}<div className="mock-client-grid">{filtered.map(client=><button className="mock-client-card" key={client.id} onClick={()=>navigate(`/clients/${client.id}`)}><span className="mock-client-avatar mock-client-avatar--blue">{initials(client.displayName)}</span><span><strong>{client.displayName}</strong><small>{client.email}</small></span><span className="mock-client-projects">{client.projectCount} {client.projectCount===1?"projeto":"projetos"}</span><ChevronRight size={18}/></button>)}</div>{!error && !filtered.length && <p>Não existem clientes a apresentar.</p>}{invite && <div className="mock-dialog-backdrop"><form className="mock-surface mock-dialog" onSubmit={submitInvite}><button type="button" className="mock-icon-button" aria-label="Fechar" onClick={()=>setInvite(false)}><X/></button><h2>Convidar cliente</h2>{sent ? <p>Convite preparado para {email}. O envio será disponibilizado numa próxima versão.</p> : <><label className="mock-field">Email do cliente<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoFocus/></label><button className="primary-action">Preparar convite</button></>}</form></div>}</PortalShell>;
}
export function ClientDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [client,setClient] = useState<ClientDetail|null>(null); const [projects,setProjects] = useState<Project[]>([]); const [notes,setNotes] = useState(""); const [error,setError] = useState(""); const load = () => { if (!id) return; getClient(id).then(c=>{setClient(c);setNotes(c.internalNotes);}).catch(e=>setError(e.message)); };
  useEffect(load,[id]); useEffect(()=>{ if (client?.canManageProjects) getProjects().then(setProjects).catch(e=>setError(e.message)); },[client?.canManageProjects]);
  const save = async () => { if (!id) return; try { await saveClientNotes(id,notes); } catch(e) { setError(e instanceof Error?e.message:"Erro ao guardar."); } };
  const associate = async (projectId: number) => { if (!id) return; await associateClientProject(id,projectId); load(); };
  const remove = async (projectId:number) => { if (!id) return; await removeClientProject(id,projectId); load(); };
  if (!client && !error) return <PortalShell><p>A carregar…</p></PortalShell>;
  if (!client) return <PortalShell><p role="alert">{error}</p></PortalShell>;
  const unassigned = projects.filter(p=>!p.client);
  return <PortalShell><button className="mock-back-link" onClick={()=>navigate("/clients")}><ArrowLeft size={17}/>Clientes</button><header className="mock-page-header"><div><h1>{client.displayName}</h1><p>Dados do cliente e projetos associados.</p></div><button className="primary-action" onClick={save}>Guardar notas</button></header>{error && <p role="alert">{error}</p>}<div className="mock-client-detail-grid"><div className="mock-form-column"><section className="mock-surface"><div className="mock-section-title"><div><h2>Informação do cliente</h2><p>Dados de identificação e contacto.</p></div></div><div className="mock-form-grid"><label className="mock-field">Nome completo<input readOnly value={client.fullName}/></label><label className="mock-field">Nome de apresentação<input readOnly value={client.displayName}/></label><label className="mock-field">NIF<input readOnly value={client.nif}/></label><label className="mock-field">Email<input readOnly value={client.email}/></label><label className="mock-field">Telefone<input readOnly value={client.phoneNumber}/></label><label className="mock-field mock-field--wide">Morada<input readOnly value={client.address}/></label><label className="mock-field mock-field--wide">Notas internas<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div></section><section className="mock-surface"><div className="mock-section-title"><div><h2>Projetos associados</h2><p>{client.projects.length} projetos com acesso.</p></div>{client.canManageProjects && <select aria-label="Associar projeto" defaultValue="" onChange={e=>{if(e.target.value) associate(Number(e.target.value));e.currentTarget.value="";}}><option value="">Associar projeto</option>{unassigned.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select>}</div>{client.projects.map(p=><div className="mock-compact-project" key={p.id}><div><strong>{p.title}</strong><small>{p.code} · {phaseLabel(p.currentPhaseCode) ?? "Sem fase atual"}</small></div>{client.canManageProjects && <button type="button" onClick={()=>remove(p.id)}>Remover</button>}</div>)}</section></div><aside className="mock-client-sidebar"><section className="mock-surface mock-client-identity"><span className="mock-client-avatar mock-client-avatar--blue">{initials(client.displayName)}</span><dl><div><dt>Contacto</dt><dd><Mail size={14}/>{client.email}</dd></div></dl></section></aside></div></PortalShell>;
}
